linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/dramf/)
      - blank
      - dot
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    disabled-checks:
      - appendAssign
      - unnamedResult
      - whyNoLint
      - indexAlloc
      - octalLiteral
      - hugeParam
      - rangeValCopy
      - regexpSimplify
      - sloppyReassign
      - commentedOutCode
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
  gocyclo:
    min-complexity: 20
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  gosec:
    excludes:
      - G101
      - G114
      - G115
      - G204
      - G304
      - G402
  revive:
    ignore-generated-header: true
  testifylint:
    enable-all: true
run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - bodyclose
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unused
    - usestdlibvars

