name: Test
on:
  pull_request:
    branches:
      - main
env:
  GO_VERSION: '1.23.2'

jobs:
  unittest:
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-12 ]

    name: Test
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Go mod tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "Run 'go mod tidy' and push it"
            exit 1
          fi
      - name: Install plugin from repository
        run: |
          trivy plugin install github.com/dramf/md?ref=${{ github.event.pull_request.head.sha }}
          trivy plugin info md
          rm -rf ~/.trivy/plugins/md

      - name: Install plugin from local file
        run: |
          go build ./
          mkdir -p ~/.trivy/plugins/md
          cp md plugin.yaml ~/.trivy/plugins/md/
          trivy plugin info md
          rm -rf ~/.trivy/plugins/md

      - name: Run unit tests
        run: go test -v -short -timeout 30s -coverprofile=coverage.txt -covermode=atomic ./...
